services:
  db:
    image: postgres:11.12
    container_name: db
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - ./dbdata:/var/lib/postgresql/data

networks:
  app-net:
